version: '3.5'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docker_xxx
    environment:
      - MYSQL_ROOT_PASSWORD=vlad
  node:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - docker_xxx
    environment:
      - PORT=3000
      - DB_HOST=db
      - NODE_ENV=test
      - WAIT_HOSTS=db:3306
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - '8080:80'
    environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: vlad
    networks:
        - docker_xxx
networks:
  docker_xxx:
    driver: bridge